### ISSUE TITLE
Tree Generator Algoritm

### ISSUE THREAD

**Issue by lucasvenez** [lucasvenez/RQL2SQL#8]
For solving #1, it is required to create the [syntax tree](https://en.wikipedia.org/wiki/Abstract_syntax_tree) first. For that, consult the precedence order between relational operations below:

1. Projection (£), Selection (¢), and Renaming (§);
2. Cross-join (X), and Natural Join (|X|);
3. Intersection (~); and
4. Union (U), and difference (-).

It is also required to consult the logical and arithmetic operations precedence described [here ](https://en.wikipedia.org/wiki/Logical_connective#Order_of_precedence) and [here](https://en.wikipedia.org/wiki/Order_of_operations), respectively.

**Comment by derickwelman** [comment]
Package syntacticTree created for this issue
